### ISSUE TITLE
Support iOS 12 ???

### ISSUE THREAD

**Issue by NguyenASang** [Paisseon/PaiBloxx#1]
Can you make this support iOS 12 pls :((

**Comment by Paisseon** [comment]
0.2b has this ^^

**Comment by NguyenASang** [comment]
thank you :3

**Comment by NguyenASang** [comment]
@Paisseon Can you change the "About" from

![image](https://user-images.githubusercontent.com/87893636/148310313-8a984ce9-cc62-4b05-a3bb-ec11530fefea.png)

to

![image](https://user-images.githubusercontent.com/87893636/148310354-bea9b138-ed4a-4906-9ac4-e86558602ae3.png)

**Comment by Paisseon** [comment]
Ah, sure.
