### ISSUE TITLE
Broke my browser even when i unistall the tweak and have tweak injection enabled

### ISSUE THREAD

**Issue by lunyaUwU** [Paisseon/PaiBloxx#2]

**Comment by Paisseon** [comment]
Try enabling/disabling Airplane Mode or running `ldrestart` as root

**Comment by lunyaUwU** [comment]
Those steps didnt help (btw i also tried to do a restore rootfs but that didnt help aswell

**Comment by Paisseon** [comment]
Everything is located in /var so rootfs wouldn't change anything. Can you confirm that both of the following files have been removed:

/var/Managed Preferences/mobile/com.apple.SystemConfiguration.plist
/var/mobile/Media/com.apple.SystemConfiguration.plist

**Comment by lunyaUwU** [comment]
Yes

**Comment by Paisseon** [comment]
Then it's not anything PaiBloxx is doing. To clarify, by breaking your browser do you mean that the internet can't connect (including in other apps, e.g. Discord) or just in one browser?

**Comment by lunyaUwU** [comment]
Its webkit in general

**Comment by Paisseon** [comment]
But you are able to for example load Reddit posts in Apollo, or view messages on Discord, or other things which use internet connection but not WebKit?

**Comment by lunyaUwU** [comment]
Ye

**Comment by Paisseon** [comment]
Then it's definitely not a PaiBloxx issue, as that would affect all network connections. Could well be a stock iOS issue, I had some of those w/ WebKit on 15.7.1.

**Comment by 01M** [comment]
Same issue. iOS 15.7.5 Installed PaiBloxx 1.1.2, now safari and other browsers won't open any pages. I don't know what to do 😢
